language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - "0.10"

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!

#before_script:
install:
  - npm install zerorpc
 # - bundle install
 # - bundle exec rakep

script: node client.js

notifications:
  email:
    - "rafi.pathan29@gmail.com" 
env:
  matrix:
  - BROWSER=firefox
  #- BROWSER=ie # will be added when we have completed SauceLabs CI
  #- BROWSER=safari # will be added after #247 merged

